---
title: "Sample Visualization"
author: "Jessica French"
date:  "`r Sys.Date()`"
output: "pdf_document"
classoption: landscape
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r label = "Load Packages", include = FALSE}
# Load in libraries
library(tidyverse)
library(sf)
library(tmap)
library(ncdf4)
library(terra)
library(janitor)
library(spData)
```



```{r label = "Read in AOI", include = FALSE}
## Read in the boundary data
# Read in the shape file of the area of interest
AOI <- st_read("/Users/jfrench/Documents/MEDS/Capstone/DATA/New_AOI_SBchannel_shp/New_AOI_SBchannel.shp")

# Read in expanded AOI for filtering large data sets
Expanded_AOI <- st_read("/Users/jfrench/Documents/MEDS/Capstone/DATA/expanded_AOI/Expaned_AOI_SBchannel.shp")
```

```{r label = "Read in Boundaries", include = FALSE}
# Read in state and federal boundaries
federal_boundaries <- st_read("/Users/jfrench/Documents/MEDS/Capstone/DATA/maritime_boundaries/federal_boundaries/USMaritimeLimitsNBoundaries.shp") |> 
  st_filter(Expanded_AOI)

# Read in national park boundaries
National_parks <- st_read("/Users/jfrench/Documents/MEDS/Capstone/DATA/nps_boundary/nps_boundary.shp") |> 
 st_transform(crs = "EPSG: 4326") |> 
  st_make_valid() |> 
  st_filter(Expanded_AOI)

# Read in California MPA boundaries
MPA_boundaries <- st_read("/Users/jfrench/Documents/MEDS/Capstone/DATA/MPAs/mpa_ca_4326 (1)/mpa_ca_4326Polygon.shp")|> 
  st_filter(Expanded_AOI)

# Read in state of California boundary
california <- st_read("/Users/jfrench/Documents/MEDS/Capstone/DATA/cb_2018_us_state_5m/cb_2018_us_state_5m.shp") |> 
  st_transform(crs = "EPSG: 4326")
```



```{r label = "Read in CalCOFI", include = FALSE}
## Read in the nutrient data

#-   CalCOFI data has nitrogen species and phosphorous goes back past 2014
# Read in CalCOFI cast data
CalCOFI_cast <- read_csv("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/CalCOFI_Database_194903-202001_csv_22Sep2021/194903-202001_Cast.csv") |> 
  filter(Year >= 2014) |> 
  dplyr::select(c("Cst_Cnt", "Quarter", "Year", "Lat_Dec", "Lon_Dec")) 

# Read in the CalCOFI bottle data
CalCOFI_bottle <- read_csv("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/CalCOFI_Database_194903-202001_csv_22Sep2021/194903-202001_Bottle.csv", locale=locale(encoding="latin1")) |> 
  right_join(CalCOFI_cast, by = "Cst_Cnt")|> 
  st_as_sf(coords = c(lon = "Lon_Dec", lat = "Lat_Dec"), crs = "EPSG: 4326") |> 
  st_filter(Expanded_AOI)
  
```



```{r label = "Read in LTER Nitrogen", include = FALSE}
#-   The LTER Biomass and environmental drivers dataset only has nitrogen and wave action
#-   Goes back past 2014
# Read in the LTER Biomass and Nitrogen Data Set
LTER_nutrients_biomass <- read_csv("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/Nitrate_LTER/kelp_no3_waves_quarterly_long (1).csv") |> 
  filter(year >= 2014)

# Read in the LTER sampling locations
LTER_locations <- read_csv("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/Nitrate_LTER/locations (1).csv")

# Combine the locations to the nutrient data
lter_data_geom <- left_join(LTER_nutrients_biomass, LTER_locations, by = "site_id") |> 
  st_as_sf(coords = c(lon = "lon", lat = "lat"), crs = "EPSG:4326")
```



```{r label = "Read in Plumes and Blooms", include = FALSE}
#-   Plumes and Blooms Data has nitrogen species and phosphorous
#-   From before 1995 to 2016
# Read in the plumes and blooms data
plumes_blooms <- read_csv("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/plumes_blooms/Plumes_and_Blooms_bottle_file_data.csv", na = c('-999.00000', '-999', ""))|>
  mutate("DATE" = lubridate::ymd(DATE),
         "LON" = LON*-1)|>
  filter(DATE >= 2014-01-01,
         LON < 100,
         LAT >= 30 & LAT <= 40) |>
  st_as_sf(coords = c(lon = "LON", lat = "LAT"), crs = "EPSG:4326")
```



```{r label = "Read in USGS Bottle", include = FALSE}
#-   USGS Bottle Data from OCT and NOV 2018 and 2019
# Read in USGS bottle data 2018
USGS_2018 <- read_csv("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/usgs_bottle_fall/SH-18-12_BTL_CTD_data_v3.0.csv") |> 
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = 4326) |> 
  st_filter(Expanded_AOI)

# Read in USGS bottle data 2019
USGS_2019 <- read_csv("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/usgs_bottle_fall/RL-19-05_BTL_CTD_data v2.0.csv") |> 
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = 4326) |> 
  st_filter(Expanded_AOI)

```



```{r label = "Read in LTER Water Chemistry",  include = FALSE}
#-   LTER Water Chemistry data
# Read in the Bottle file from LTER

LTER_bottle <- read_csv2("/Users/jfrench/Documents/MEDS/Capstone/DATA/Nutrients/LTER_bottle/LTER_monthly_bottledata_20220930.txt") |> 
  clean_names() |> 
  filter(longitude_e < 0) |> 
  dplyr::select(po4_umol_l, no2_no3_umol_l, latitude_n, longitude_e)

stringi::stri_sub(LTER_bottle$latitude_n, 3, 2) = '.' 
stringi::stri_sub(LTER_bottle$longitude_e, 5, 4) <- '.'
#Encoding(LTER_bottle$comments <- "UTF-8")

LTER_bottle <- LTER_bottle |> 
  mutate("latitude_n" = as.numeric(latitude_n),
         "longitude_e" = as.numeric(longitude_e)) |> 
  st_as_sf(coords = c("longitude_e", "latitude_n"), 
           crs = 4326) 
```

```{r label = "Map", fig.cap="Map showing location of nutrient samples from different data sets. Relevant regulatory boundaries are also shown.", message=FALSE, fig.ext='pdf', fig.height=16, fig.width=16}
# Test map
tmap_mode(mode = "plot")

  tm_shape(california) +
  tm_polygons() +
  tm_shape(National_parks) +
  tm_borders(col = "#416248") +
  tm_shape(MPA_boundaries) +
  tm_borders(col = "#904934") +
  tm_shape(CalCOFI_bottle) +
  tm_dots(col = "#fcdc55") +
  tm_shape(lter_data_geom) + 
  tm_dots(col = "#4c6a87") +
  tm_shape(plumes_blooms) +
  tm_dots(col = "#fb967f") +
  tm_shape(USGS_2018) +
  tm_dots(col = "#C9A2BF") +
  tm_shape(USGS_2019) +
  tm_dots(col = "#C9A2BF") +
  tm_shape(LTER_bottle) +
  tm_dots(col = "#57b7b4") +
  tm_shape(federal_boundaries) +
  tm_lines(col = "black") +
  tm_shape(AOI, is.master = TRUE) +
  tm_borders(col = "#801818", lwd = 2) +
  tm_layout(outer.margins = c(.1, .1, .1, .1), 
            inner.margins = c(.05, .05, .05, .05),
            legend.outside = TRUE, 
            main.title = "KelpGeoMod Nutrient Data Distribution") +
  tm_add_legend('symbol', 
	col = c("#fcdc55", "#4c6a87", "#fb967f", "#C9A2BF", "#57b7b4"),
	border.col = "grey40",
	size = 0.7,
	labels = c("CalCOFI Bottle Samples", "SBC LTER Water Samples", "Plumes and Blooms Bottle Samples", "USGS Bottle Samples", "SBC LTER Bottle Samples"),
	title="Legend") +
    tm_add_legend("line",
                  lwd = 2,
                  col = c("#416248", "#904934" , "black", "#801818"),
                  labels = c("National Parks", 
                             "MPAs", 
                             "Federal Jurisdiction Boundary",
                             "Area of Interest"))
  
```
